[package]
name = "jockey_tests"
version = "0.0.0"
authors = ["Richard Wiedenhöft <richard@wiedenhoeft.xyz>"]
publish = false

[lib]
doc = false

[[bin]]
name = "jockey_tests"
path = "src/main.rs"

[dependencies]
jockey = { path = "../jockey" }
jockey_derive = { path = "../jockey_derive" }
